#!/usr/bin/env node
/**
 * Vendor the Meta Graph client from a gpp-mcp checkout.
 *
 * Maintainer tooling. gpp-mcp is a private monorepo; you do not need it to use
 * this package, because the vendored client under src/vendor/ is complete.
 *
 * This copies the client only. The server layer above it is hand-ported and
 * owned by this repository — see the design spec §4 for why.
 *
 * Safe to re-run: src/vendor and test/vendor are replaced wholesale.
 *
 *   node scripts/extract.mjs [path-to-gpp-mcp]
 */
import { execFileSync } from "node:child_process"
import { cpSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs"
import { basename, dirname, join, resolve } from "node:path"
import { fileURLToPath } from "node:url"

const HERE = dirname(fileURLToPath(import.meta.url))
const REPO = resolve(HERE, "..")
const SOURCE = resolve(process.argv[2] ?? join(REPO, "..", "gpp-mcp"))

const CLIENT = join(SOURCE, "packages/meta-client")
const VENDOR_SRC = join(REPO, "src/vendor/meta-client")
const VENDOR_TEST = join(REPO, "test/vendor")

/**
 * Copied verbatim. Relative imports inside these resolve unchanged.
 *
 * `index.ts` is the upstream barrel and `types.ts` the Marketing structural
 * types. Both are copied whole rather than trimmed: this package needs the
 * Marketing surface to resolve an ad to the Page post behind it, which is the
 * only route to ad comments. Some exports go unused, as with the Marketing
 * field lists already carried in `constants.ts` — the script stays a copier
 * rather than a surgeon.
 */
const SRC_FILES = ["constants.ts", "http.ts", "errors.ts", "types.ts", "index.ts"]
const SRC_DIRS = ["pages"]

/**
 * The client tests that cover the vendored surface. `client.test.ts` and
 * `regressions.test.ts` exercise the Marketing API, which is not vendored.
 */
const TEST_FILES = [
  "http.test.ts",
  "pagination.test.ts",
  "retry.test.ts",
  "pages-client.test.ts",
  "pages-normalize.test.ts",
  "client.test.ts",
  "regressions.test.ts",
]

function fail(message) {
  console.error(`extract: ${message}`)
  process.exit(1)
}

function git(...args) {
  return execFileSync("git", ["-C", SOURCE, ...args], { encoding: "utf8" }).trim()
}

// A vendored copy that corresponds to no commit cannot be reasoned about later.
let sha
try {
  sha = git("rev-parse", "HEAD")
} catch {
  fail(`${SOURCE} is not a git repository`)
}

const dirty = git("status", "--porcelain", "--", "packages/meta-client")
if (dirty) {
  fail(
    "source has uncommitted changes under packages/meta-client:\n" +
      dirty +
      "\nCommit them first — a vendored copy must correspond to a commit.",
  )
}

/**
 * Identify the source by remote URL, never by local path — this file is
 * committed, and an absolute path leaks the extracting machine's layout.
 */
let origin
try {
  origin = normalizeOrigin(git("remote", "get-url", "origin"))
} catch {
  origin = basename(SOURCE)
}

/** Reduce a git remote URL (SSH alias, ssh://, git@host:, or https://) to owner/repo. */
function normalizeOrigin(url) {
  const match = url.replace(/\.git$/, "").match(/[:/]([^/:]+\/[^/:]+)$/)
  return match ? match[1] : url
}

rmSync(VENDOR_SRC, { recursive: true, force: true })
rmSync(VENDOR_TEST, { recursive: true, force: true })
mkdirSync(VENDOR_SRC, { recursive: true })
mkdirSync(VENDOR_TEST, { recursive: true })

const GENERATED = "// Generated by scripts/extract.mjs. Do not edit; fix upstream and re-extract.\n"

for (const file of SRC_FILES) {
  const body = readFileSync(join(CLIENT, "src", file), "utf8")
  writeFileSync(join(VENDOR_SRC, file), GENERATED + body)
}

for (const dir of SRC_DIRS) {
  cpSync(join(CLIENT, "src", dir), join(VENDOR_SRC, dir), { recursive: true })
}

// Tests import ../src/x.js upstream; here the client sits two levels deeper.
for (const file of TEST_FILES) {
  const body = readFileSync(join(CLIENT, "test", file), "utf8")
  const rewritten = body.replaceAll('from "../src/', 'from "../../src/vendor/meta-client/')
  writeFileSync(join(VENDOR_TEST, file), GENERATED + rewritten)
}

writeFileSync(
  join(VENDOR_SRC, "VENDOR.md"),
  `# Vendored Meta Graph client

Generated by \`scripts/extract.mjs\`. **Do not edit these files.** A fix belongs
upstream in gpp-mcp, followed by \`npm run extract\`.

| | |
|---|---|
| Source | \`${origin}\` |
| Commit | \`${sha}\` |
| Extracted | ${new Date().toISOString().slice(0, 10)} |

Copied: ${SRC_FILES.join(", ")}, ${SRC_DIRS.join(", ")}/ and ${TEST_FILES.length} test files.

Everything under \`src/\` is copied, including the Marketing API surface, which
this package uses to resolve an ad to the Page post behind it. Nothing here is
hand-written — earlier versions of this script generated the barrel; it no
longer does.
`,
)

console.log(`extract: vendored from ${sha.slice(0, 7)}`)
console.log(`  src  -> src/vendor/meta-client/`)
console.log(`  test -> test/vendor/ (${TEST_FILES.length} files)`)
