#!/usr/bin/env node
/**
 * Generate `docs/` from the broadkast articles, instead of keeping two copies
 * in step by hand.
 *
 *   node scripts/sync-docs.mjs            # write docs/ from the source
 *   node scripts/sync-docs.mjs --check    # exit 1 if docs/ is not what it would write
 *   node scripts/sync-docs.mjs --from <dir>
 *
 * **Why this exists.** Three documents live twice: once in the broadkast
 * content repo, which publishes to the website, and once in `docs/`, so the
 * README can link to something that renders on GitHub and does not depend on a
 * site being live. Nothing held the two in step, and on 2026-09-15 they had
 * drifted in BOTH directions at once — the source article was missing a finding
 * its own derivative carried, and the derivative was missing a summary bullet
 * the source had. A manual `diff` was the only thing that found it, and it was
 * only run because somebody happened to ask.
 *
 * Detecting drift and removing it are different fixes. This is the second:
 * `docs/` is now output, and the way to change it is to change the source.
 *
 * **The source is broadkast**, which is what the derivative already claimed in
 * its own header long before anything enforced it.
 */
import { readFileSync, writeFileSync } from "node:fs"
import { join, resolve } from "node:path"

const REPO = resolve(import.meta.dirname, "..")

/** Default location of the content repo, as a sibling checkout. */
const DEFAULT_SOURCE = resolve(
  REPO,
  "..",
  "broadkast",
  "docs",
  "my social media posts",
  "Founder_Ecosystem_Command_Center Rewrite",
  "GrasshopperPebbles",
  "grasshopperpebbles articles",
  "facebook-engagement-mcp-setup",
)

/**
 * Source article → generated doc.
 *
 * `docs/get-your-token.md` and `docs/system-user-token.md` are deliberately
 * absent: they have no article in the bundle, so they are written by hand and
 * this script must never touch them.
 */
const PAIRS = [
  { article: "article.md", doc: "setup-tokens-permissions.md" },
  { article: "article-dark-posts.md", doc: "dark-posts.md" },
  { article: "article-error-messages.md", doc: "publish-actions-error.md" },
]

/** Frontmatter keys the generated copy keeps. Everything else is for the site. */
const KEEP_FRONTMATTER = ["title", "date", "verified"]

/**
 * Published slugs that have a counterpart in `docs/`.
 *
 * A slug that is NOT here belongs to an article in the wider corpus with no
 * copy in this repository. Its link is stripped to plain text rather than left
 * pointing at a parked domain — which is what the generated copies already did
 * by hand, and the reason matters: `grasshopperpebbles.com` answers 200 for
 * every path including nonsense, so a link check cannot tell a real page from a
 * missing one. Text that is honestly not a link beats a link that cannot fail.
 */
const SLUG_TO_DOC = new Map([
  ["facebook-page-comments-graph-api-setup-tokens-permissions", "setup-tokens-permissions.md"],
  ["facebook-feed-missing-posts-ad-comments-token", "dark-posts.md"],
  ["facebook-graph-api-publish-actions-deprecated-error", "publish-actions-error.md"],
])

const GITHUB = "https://github.com/grasshopperpebbles/facebook-engagement-mcp"

const NOTICE = `<!-- Generated by scripts/sync-docs.mjs from the broadkast content repo,
     under grasshopperpebbles articles/facebook-engagement-mcp-setup/.
     Do not edit this file: edit the article and re-run the script. This copy
     exists so the README can link to something that renders code correctly and
     does not depend on a site being live. -->`

/** Split a document into its frontmatter block and the rest. */
function splitFrontmatter(text) {
  if (!text.startsWith("---\n")) return { frontmatter: "", body: text }
  const end = text.indexOf("\n---\n", 4)
  if (end === -1) return { frontmatter: "", body: text }
  return { frontmatter: text.slice(4, end + 1), body: text.slice(end + 5) }
}

/**
 * Keep only the frontmatter the repo copy needs.
 *
 * Line-based on purpose rather than a YAML parse: the only multi-line value here
 * is `keywords`, which is dropped, and a continuation line is recognised by its
 * indent. A dependency-free script that cannot mangle a quoted colon is worth
 * more than one that handles YAML it will never see.
 */
function filterFrontmatter(frontmatter) {
  const byKey = new Map()
  let current = null

  for (const line of frontmatter.split("\n")) {
    if (line.length === 0) continue
    if (/^\s/.test(line)) {
      if (current) byKey.set(current, `${byKey.get(current)}\n${line}`)
      continue
    }
    const key = line.slice(0, line.indexOf(":"))
    current = KEEP_FRONTMATTER.includes(key) ? key : null
    if (current) byKey.set(current, line)
  }

  // Emitted in KEEP_FRONTMATTER order, not the source's. The articles do not
  // agree on key order among themselves, and output that reshuffles by source
  // makes every regeneration look like a change.
  return KEEP_FRONTMATTER.filter((key) => byKey.has(key))
    .map((key) => byKey.get(key))
    .join("\n")
}

/**
 * Site links and GitHub URLs become paths relative to `docs/`.
 *
 * Relative rather than absolute deliberately: `links.test.ts` verifies relative
 * targets and their anchors offline, and skips absolute URLs it cannot check. A
 * generated file that used absolute links would silently leave that check.
 */
function rewriteLinks(body) {
  let out = body

  // `[text](/application-development/<slug>#frag)` → `[text](./<doc>#frag)`,
  // or plain text when this repository has no copy of that article.
  out = out.replace(
    /\[([^\]]+)\]\(\/application-development\/([a-z0-9-]+)(#[^)]*)?\)/g,
    (whole, text, slug, fragment = "") => {
      const doc = SLUG_TO_DOC.get(slug)
      return doc ? `[${text}](./${doc}${fragment})` : text
    },
  )

  // Repository URLs → paths from `docs/`.
  out = out.replaceAll(`${GITHUB}/blob/main/docs/`, "./")
  out = out.replaceAll(`${GITHUB}/blob/main/`, "../")
  // The repo root and /releases have no file to point at and stay absolute.

  return out
}

function generate(articleText) {
  const { frontmatter, body } = splitFrontmatter(articleText)
  const kept = filterFrontmatter(frontmatter)
  return `---\n${kept}\n---\n\n${NOTICE}\n${rewriteLinks(body).replace(/^\n+/, "\n")}`
}

const args = process.argv.slice(2)
const check = args.includes("--check")
const fromFlag = args.indexOf("--from")
const source = fromFlag === -1 ? DEFAULT_SOURCE : resolve(args[fromFlag + 1] ?? "")

let sourceReadable = true
try {
  readFileSync(join(source, PAIRS[0].article), "utf8")
} catch {
  sourceReadable = false
}

if (!sourceReadable) {
  // A missing content repo is not a failure. It is the ordinary state of a
  // clone that has only this repository, and of CI.
  console.error(
    `Content repo not found at:\n  ${source}\n\n` +
      "docs/ is generated from it. Nothing was checked or written. Pass --from " +
      "<dir> if it lives elsewhere.",
  )
  process.exit(check ? 0 : 1)
}

const drifted = []
for (const { article, doc } of PAIRS) {
  const generated = generate(readFileSync(join(source, article), "utf8"))
  const target = join(REPO, "docs", doc)

  if (check) {
    const current = readFileSync(target, "utf8")
    if (current !== generated) drifted.push({ doc, article })
    continue
  }

  writeFileSync(target, generated)
  console.log(`docs/${doc}  <-  ${article}`)
}

if (check) {
  if (drifted.length === 0) {
    console.log(`docs/ matches the source articles (${PAIRS.length} documents).`)
    process.exit(0)
  }
  console.error("docs/ has drifted from the articles it is generated from:\n")
  for (const { doc, article } of drifted) console.error(`  docs/${doc}  <-  ${article}`)
  console.error(
    "\nIf the change belongs in the docs, it belongs in the ARTICLE. Edit the " +
      "article and run `node scripts/sync-docs.mjs`. Editing docs/ directly " +
      "cannot survive the next sync.",
  )
  process.exit(1)
}
